name: "Auto Check in Shopee"

on:
  schedule:
    - cron: "0 17 * * *"  # scheduled at 00:00 (GMT+7) everyday
  workflow_dispatch:

env:
  RUN_ENV: 'prod'
  # You can change the time zone according to your area
  TZ: 'Asia/Ho_Chi_Minh'

jobs:
  build:
    name: "Build"

    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          # ref: master

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      #- name: Random sleep
        #if: github.event_name == 'schedule'
        #run: sleep $(shuf -i 10-300 -n 1)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run sign
        env:
          OS_COOKIE: ${{ secrets.OS_COOKIE }}
        run: |
          python3 ./shopee.py
